import { Component, inject } from '@angular/core';
import { ControlContainer, ReactiveFormsModule } from '@angular/forms';
import { CustomInput } from '../../../form-controls/custom-input/custom-input';
import { Select } from '../../../form-controls/select/select';
import { TelInput } from '../../../form-controls/tel-input/tel-input';
import { TranslatePipe } from '../../../../pipes/translate-pipe';
import { TranslationService } from '../../../../services/translation-service';

@Component({
  selector: 'app-basic-data-step',
  imports: [CustomInput, TelInput, Select, ReactiveFormsModule, TranslatePipe],
  templateUrl: './basic-data-step.html',
  styleUrl: './basic-data-step.scss',
  viewProviders: [
    {
      provide: ControlContainer,
      useFactory: () => inject(ControlContainer, { skipSelf: true }),
    },
  ],
})
export class BasicDataStep {
  private translationService = inject(TranslationService);

  countriesOptions = [
    { value: 'af', label: 'registration.basicData.country.options.af' },
    { value: 'al', label: 'registration.basicData.country.options.al' },
    { value: 'dz', label: 'registration.basicData.country.options.dz' },
    { value: 'ad', label: 'registration.basicData.country.options.ad' },
    { value: 'ao', label: 'registration.basicData.country.options.ao' },
    { value: 'ar', label: 'registration.basicData.country.options.ar' },
    { value: 'am', label: 'registration.basicData.country.options.am' },
    { value: 'au', label: 'registration.basicData.country.options.au' },
    { value: 'at', label: 'registration.basicData.country.options.at' },
    { value: 'az', label: 'registration.basicData.country.options.az' },
    { value: 'bh', label: 'registration.basicData.country.options.bh' },
    { value: 'bd', label: 'registration.basicData.country.options.bd' },
    { value: 'by', label: 'registration.basicData.country.options.by' },
    { value: 'be', label: 'registration.basicData.country.options.be' },
    { value: 'bz', label: 'registration.basicData.country.options.bz' },
    { value: 'bj', label: 'registration.basicData.country.options.bj' },
    { value: 'bo', label: 'registration.basicData.country.options.bo' },
    { value: 'ba', label: 'registration.basicData.country.options.ba' },
    { value: 'br', label: 'registration.basicData.country.options.br' },
    { value: 'bg', label: 'registration.basicData.country.options.bg' },
    { value: 'ca', label: 'registration.basicData.country.options.ca' },
    { value: 'cl', label: 'registration.basicData.country.options.cl' },
    { value: 'cn', label: 'registration.basicData.country.options.cn' },
    { value: 'co', label: 'registration.basicData.country.options.co' },
    { value: 'cr', label: 'registration.basicData.country.options.cr' },
    { value: 'hr', label: 'registration.basicData.country.options.hr' },
    { value: 'cu', label: 'registration.basicData.country.options.cu' },
    { value: 'cy', label: 'registration.basicData.country.options.cy' },
    { value: 'cz', label: 'registration.basicData.country.options.cz' },
    { value: 'dk', label: 'registration.basicData.country.options.dk' },
    { value: 'do', label: 'registration.basicData.country.options.do' },
    { value: 'ec', label: 'registration.basicData.country.options.ec' },
    { value: 'eg', label: 'registration.basicData.country.options.eg' },
    { value: 'ee', label: 'registration.basicData.country.options.ee' },
    { value: 'fi', label: 'registration.basicData.country.options.fi' },
    { value: 'fr', label: 'registration.basicData.country.options.fr' },
    { value: 'ge', label: 'registration.basicData.country.options.ge' },
    { value: 'de', label: 'registration.basicData.country.options.de' },
    { value: 'gr', label: 'registration.basicData.country.options.gr' },
    { value: 'hu', label: 'registration.basicData.country.options.hu' },
    { value: 'is', label: 'registration.basicData.country.options.is' },
    { value: 'in', label: 'registration.basicData.country.options.in' },
    { value: 'id', label: 'registration.basicData.country.options.id' },
    { value: 'ir', label: 'registration.basicData.country.options.ir' },
    { value: 'iq', label: 'registration.basicData.country.options.iq' },
    { value: 'ie', label: 'registration.basicData.country.options.ie' },
    { value: 'il', label: 'registration.basicData.country.options.il' },
    { value: 'it', label: 'registration.basicData.country.options.it' },
    { value: 'jp', label: 'registration.basicData.country.options.jp' },
    { value: 'jo', label: 'registration.basicData.country.options.jo' },
    { value: 'kz', label: 'registration.basicData.country.options.kz' },
    { value: 'ke', label: 'registration.basicData.country.options.ke' },
    { value: 'kr', label: 'registration.basicData.country.options.kr' },
    { value: 'kg', label: 'registration.basicData.country.options.kg' },
    { value: 'lv', label: 'registration.basicData.country.options.lv' },
    { value: 'lb', label: 'registration.basicData.country.options.lb' },
    { value: 'lt', label: 'registration.basicData.country.options.lt' },
    { value: 'lu', label: 'registration.basicData.country.options.lu' },
    { value: 'my', label: 'registration.basicData.country.options.my' },
    { value: 'mx', label: 'registration.basicData.country.options.mx' },
    { value: 'md', label: 'registration.basicData.country.options.md' },
    { value: 'mc', label: 'registration.basicData.country.options.mc' },
    { value: 'mn', label: 'registration.basicData.country.options.mn' },
    { value: 'ma', label: 'registration.basicData.country.options.ma' },
    { value: 'np', label: 'registration.basicData.country.options.np' },
    { value: 'nl', label: 'registration.basicData.country.options.nl' },
    { value: 'nz', label: 'registration.basicData.country.options.nz' },
    { value: 'ng', label: 'registration.basicData.country.options.ng' },
    { value: 'no', label: 'registration.basicData.country.options.no' },
    { value: 'pk', label: 'registration.basicData.country.options.pk' },
    { value: 'pa', label: 'registration.basicData.country.options.pa' },
    { value: 'py', label: 'registration.basicData.country.options.py' },
    { value: 'pe', label: 'registration.basicData.country.options.pe' },
    { value: 'ph', label: 'registration.basicData.country.options.ph' },
    { value: 'pl', label: 'registration.basicData.country.options.pl' },
    { value: 'pt', label: 'registration.basicData.country.options.pt' },
    { value: 'qa', label: 'registration.basicData.country.options.qa' },
    { value: 'ro', label: 'registration.basicData.country.options.ro' },
    { value: 'ru', label: 'registration.basicData.country.options.ru' },
    { value: 'sa', label: 'registration.basicData.country.options.sa' },
    { value: 'rs', label: 'registration.basicData.country.options.rs' },
    { value: 'sg', label: 'registration.basicData.country.options.sg' },
    { value: 'sk', label: 'registration.basicData.country.options.sk' },
    { value: 'si', label: 'registration.basicData.country.options.si' },
    { value: 'za', label: 'registration.basicData.country.options.za' },
    { value: 'es', label: 'registration.basicData.country.options.es' },
    { value: 'se', label: 'registration.basicData.country.options.se' },
    { value: 'ch', label: 'registration.basicData.country.options.ch' },
    { value: 'th', label: 'registration.basicData.country.options.th' },
    { value: 'tr', label: 'registration.basicData.country.options.tr' },
    { value: 'ua', label: 'registration.basicData.country.options.ua' },
    { value: 'ae', label: 'registration.basicData.country.options.ae' },
    { value: 'gb', label: 'registration.basicData.country.options.gb' },
    { value: 'us', label: 'registration.basicData.country.options.us' },
    { value: 'uy', label: 'registration.basicData.country.options.uy' },
    { value: 'uz', label: 'registration.basicData.country.options.uz' },
    { value: 've', label: 'registration.basicData.country.options.ve' },
    { value: 'vn', label: 'registration.basicData.country.options.vn' },
  ];

  get translatedCountriesOptions() {
    return this.countriesOptions.map((option) => ({
      ...option,
      label: this.translationService.translate(option.label),
    }));
  }
}
